name: Deploy Docs
on:
  push:
    branches: [main]
    paths: ["site/**"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.13"
      - run: pip install mkdocs-material mkdocs-glightbox
      - run: cd site && mkdocs gh-deploy --force
